In [1]:
import numpy as np
import xarray as xr
import netCDF4 as nc
import pandas as pd
import ES3 
from datetime import datetime

In [2]:
ds = xr.open_dataset('era5_18_21.nc')

In [3]:
df = ds.sel(longitude=-23, latitude=-43).to_dataframe()

In [4]:
df.pop('latitude')
df.pop('longitude')

time
2018-01-01 00:00:00   -23.0
2018-01-01 01:00:00   -23.0
2018-01-01 02:00:00   -23.0
2018-01-01 03:00:00   -23.0
2018-01-01 04:00:00   -23.0
                       ...
2021-12-31 19:00:00   -23.0
2021-12-31 20:00:00   -23.0
2021-12-31 21:00:00   -23.0
2021-12-31 22:00:00   -23.0
2021-12-31 23:00:00   -23.0
Name: longitude, Length: 35064, dtype: float32

In [5]:
boia1 = ES3.trata_dado('dados/SIMCOSTA_RJ-1_OCEAN_2015-07-29_2016-10-13.csv')
boia1.columns = ['Hs1', 'Tp1', 'Dir1', 'DirN1', 'Decl1']

In [6]:
boia2 = ES3.trata_dado('dados/SIMCOSTA_RJ-2_OCEAN_2015-07-29_2016-12-20.csv')
boia2.columns = ['Hs2', 'Tp2', 'Dir2', 'DirN2', 'Decl2']

In [7]:
boia3 = ES3.trata_dado('dados/SIMCOSTA_RJ-3_OCEAN_2016-07-14_2022-01-26.csv')
boia3.columns = ['Hs3', 'Tp3,', 'Dir3', 'DirN3', 'Decl3']

In [8]:
boia4 = ES3.trata_dado('dados/SIMCOSTA_RJ-4_OCEAN_2017-08-28_2022-01-25.csv')
boia4.columns = ['Hs4', 'Tp4', 'Dir4', 'DirN4', 'Decl4']

In [9]:
geral = pd.concat([boia1, boia2, boia3, boia4, df], axis=1)

In [12]:
geral.index[]

DatetimeIndex(['2015-07-29 20:25:00', '2015-07-29 21:25:00',
               '2015-07-29 22:25:00', '2015-07-29 23:25:00',
               '2015-07-30 00:25:00', '2015-07-30 01:25:00',
               '2015-07-30 02:25:00', '2015-07-30 03:25:00',
               '2015-07-30 04:25:00', '2015-07-30 05:25:00',
               ...
               '2022-01-26 19:21:40', '2022-01-26 19:51:40',
               '2022-01-26 20:21:40', '2022-01-26 20:51:40',
               '2022-01-26 21:21:40', '2022-01-26 21:51:40',
               '2022-01-26 22:21:40', '2022-01-26 22:51:40',
               '2022-01-26 23:21:40', '2022-01-26 23:51:40'],
              dtype='datetime64[ns]', length=147305, freq=None)

In [24]:
geral.loc['2015-01-01':'2019-02-01']

,Hs1,Tp1,Dir1,DirN1,Decl1,Hs2,Tp2,Dir2,DirN2,Decl2,...,DirN3,Decl3,Hs4,Tp4,Dir4,DirN4,Decl4,mdww,mwp,swh
2015-07-29 20:25:00,0.79,8.7,178.0,155.45,-22.55,0.46,10.0,174.0,151.46,-22.55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-07-29 21:25:00,0.84,9.1,178.0,155.45,-22.55,0.43,9.5,173.0,150.46,-22.55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-07-29 22:25:00,0.85,8.3,172.0,149.45,-22.55,0.35,9.1,179.0,156.46,-22.55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-07-29 23:25:00,0.84,10.0,167.0,144.45,NaN,0.39,10.0,172.0,149.46,-22.55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-07-30 00:25:00,0.81,8.3,171.0,148.45,-22.55,0.37,10.5,177.0,154.46,-22.55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-02-01 22:53:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,128.12,-22.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-02-01 22:55:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.66,15.4,161.0,138.11,-22.89,NaN,NaN,NaN
2019-02-01 23:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,275.041382,8.366951,2.557083
2019-02-01 23:23:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,125.12,-22.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-02-01 23:25:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.66,15.4,156.0,133.11,-22.89,NaN,NaN,NaN

In [10]:
geral.resample('H')

AttributeError: 'DataFrame' object has no attribute 'ressample'

In [32]:
geral['Hs4'].corr(geral['swh'])

nan

In [35]:
geral['2015-01-01':'2019-02-01']['swh']

2015-07-29 20:25:00         NaN
2015-07-29 21:25:00         NaN
2015-07-29 22:25:00         NaN
2015-07-29 23:25:00         NaN
2015-07-30 00:25:00         NaN
                         ...
2019-02-01 22:53:00         NaN
2019-02-01 22:55:00         NaN
2019-02-01 23:00:00    2.557083
2019-02-01 23:23:00         NaN
2019-02-01 23:25:00         NaN
Name: swh, Length: 73938, dtype: float32

In [48]:
hour = pd.to_timedelta(geral.index.hour, unit='H')

In [55]:
geral.groupby(hour).mean()

,Hs1,Tp1,Dir1,DirN1,Decl1,Hs2,Tp2,Dir2,DirN2,Decl2,...,DirN3,Decl3,Hs4,Tp4,Dir4,DirN4,Decl4,mdww,mwp,swh
0 days 00:00:00,1.227606,11.639928,186.101327,163.906185,-22.614943,0.486792,10.110208,163.510417,140.891792,-22.618446,...,146.845598,-22.803042,1.193666,10.561349,180.594898,157.724678,-22.872145,231.583237,9.048060,3.406093
0 days 01:00:00,1.216861,11.627932,186.521161,164.116993,-22.615320,0.484341,10.017678,164.188285,141.569571,-22.618558,...,146.396667,-22.801487,1.183635,10.635171,179.410761,156.542673,-22.869962,232.261948,9.036160,3.407401
0 days 02:00:00,1.208307,11.678979,186.916160,164.722145,-22.615058,0.483150,10.024532,164.148649,141.529969,-22.618448,...,145.943389,-22.802002,1.178414,10.646101,178.254333,155.385706,-22.870625,233.424622,9.024144,3.409829
0 days 03:00:00,1.209247,11.673576,187.192727,164.996868,-22.615423,0.484922,9.982690,164.018770,141.400177,-22.618391,...,145.900445,-22.802508,1.178351,10.601953,177.878038,155.008772,-22.871157,234.630386,9.013342,3.413893
0 days 04:00:00,1.198685,11.694654,187.432564,165.237188,-22.615057,0.481854,10.079896,165.258333,142.639615,-22.618555,...,145.466076,-22.802898,1.175266,10.620349,177.921397,155.052301,-22.871274,234.435684,9.005891,3.417018
0 days 05:00:00,1.197570,11.705091,187.192727,164.788184,-22.614994,0.480301,10.131809,166.266112,143.647287,-22.618770,...,146.110041,-22.803470,1.164723,10.633934,178.340626,155.472553,-22.869897,233.870285,8.999896,3.419423
0 days 06:00:00,1.202228,11.828083,186.908425,164.716297,-22.615309,0.472050,10.108117,167.877211,145.258502,-22.618488,...,146.246550,-22.803186,1.152632,10.615557,179.304667,156.436772,-22.869758,234.385178,8.997885,3.420627
0 days 07:00:00,1.211818,11.737377,186.183824,164.875648,-22.614955,0.469539,10.281885,168.119372,145.500796,-22.618462,...,146.603810,-22.804461,1.153118,10.683947,180.753947,157.885237,-22.870783,232.980164,8.997933,3.419271
0 days 08:00:00,1.214721,11.677342,186.341772,163.728759,-22.615007,0.475730,10.267459,167.980541,145.362216,-22.618281,...,146.902461,-22.802320,1.157296,10.745929,181.722124,158.852761,-22.870941,233.124039,9.003416,3.419742
0 days 09:00:00,1.217458,11.749424,185.688860,163.076018,-22.614891,0.478576,10.314779,167.128371,144.509741,-22.618658,...,147.277163,-22.802713,1.145919,10.665029,181.887231,159.018442,-22.870700,234.066177,9.008553,3.419487
0 days 10:00:00,1.216271,11.699242,185.430556,162.817374,-22.614665,0.482925,10.321183,163.768817,141.150226,-22.618511,...,147.835463,-22.802924,1.147263,10.713482,181.657589,158.788259,-22.871371,231.170410,9.014615,3.418894
0 days 11:00:00,1.220088,11.618892,185.244332,162.631121,-22.615000,0.484519,10.325730,161.825946,139.207589,-22.618453,...,147.725115,-22.799495,1.142370,10.739947,181.509987,158.641163,-22.870571,232.248764,9.012980,3.421679
0 days 12:00:00,1.204540,11.606258,185.834356,163.220994,-22.614915,0.480723,10.229245,161.345912,138.727631,-22.618137,...,147.739946,-22.800414,1.155578,10.712629,181.402597,158.534492,-22.870130,232.429657,9.010751,3.425847
0 days 13:00:00,1.206481,11.584815,186.001235,163.832074,-22.614714,0.480273,10.153102,162.339642,139.721346,-22.618147,...,146.748824,-22.800258,1.147424,10.670951,180.359155,157.490022,-22.871090,234.471573,9.009139,3.430043
0 days 14:00:00,1.199817,11.618215,186.366748,164.176695,-22.614910,0.480189,10.203459,163.906709,141.288071,-22.618318,...,146.521749,-22.801008,1.148915,10.726734,179.524583,156.655461,-22.871199,235.708481,9.008479,3.432703
0 days 15:00:00,1.207277,11.534921,187.710623,165.934313,-22.615071,0.485948,10.207315,164.916405,142.297837,-22.618234,...,146.585137,-22.800725,1.145755,10.761089,178.655157,155.787131,-22.870000,236.971680,9.010070,3.435780
0 days 16:00:00,1.201795,11.493651,187.581197,165.805516,-22.615160,0.488698,10.109271,165.487500,142.868615,-22.618609,...,145.914231,-22.799674,1.149724,10.734314,178.362299,155.493757,-22.870747,237.550247,9.013185,3.434669
0 days 17:00:00,1.210791,11.498175,186.042579,164.934327,-22.614750,0.489225,10.042469,165.694561,143.076015,-22.618386,...,145.984195,-22.800657,1.152464,10.683870,178.563244,155.695381,-22.869881,236.060547,9.019187,3.432591
0 days 18:00:00,1.209816,11.499510,185.996324,163.808215,-22.614749,0.487882,10.033298,166.165437,143.546997,-22.618247,...,145.635133,-22.800108,1.168521,10.671918,179.408074,156.539206,-22.871020,234.639999,9.025023,3.428231
0 days 19:00:00,1.229314,11.558824,185.208333,163.022054,-22.615071,0.492545,10.044479,166.575184,143.956667,-22.618169,...,146.149652,-22.802131,1.176449,10.634707,180.235816,157.368010,-22.869824,235.225983,9.039084,3.427604
0 days 20:00:00,1.227470,11.550365,184.928224,162.739575,-22.614929,0.495278,10.177754,165.995803,143.377692,-22.618042,...,146.541370,-22.800627,1.181538,10.636533,180.708444,157.839662,-22.871087,233.703354,9.048880,3.423582
0 days 21:00:00,1.239129,11.624667,184.541717,162.351508,-22.614562,0.494351,10.168305,165.323222,142.705000,-22.618147,...,146.772771,-22.798019,1.185437,10.530004,181.334975,158.466977,-22.870306,233.169662,9.055177,3.416226
0 days 22:00:00,1.233026,11.556501,184.323208,162.135491,-22.614910,0.495898,10.308977,165.171190,142.552985,-22.617969,...,146.957734,-22.800166,1.178970,10.500089,181.270306,158.401158,-22.871393,232.393799,9.064037,3.406540
0 days 23:00:00,1.237861,11.615431,185.020656,162.831491,-22.614656,0.493924,10.219517,164.038825,141.420493,-22.618139,...,147.137011,-22.793339,1.183776,10.457749,181.169127,158.308825,-22.863411,232.165726,9.059974,3.404768